--utf8 generated by DDM
update T_ERROR_TYPE
   set (TYPE_ID, CATE_0, CATE_1, CATE_2, ERROR_NAME, CAUSE_DEAL) =
       (select 20710020011,
               2,
               207,
               207100,
               'Indx due date is less than paidup date,Please Contact IT Support to correct the data',
               null
          from dual)
 where TYPE_ID = 20710020011;
insert into T_ERROR_TYPE
  (TYPE_ID, CATE_0, CATE_1, CATE_2, ERROR_NAME, CAUSE_DEAL)
  select 20710020011,
         2,
         207,
         207100,
         'Indx due date is less than paidup date,Please Contact IT Support to correct the data',
         null
    from dual
   where not exists
   (select * from T_ERROR_TYPE where TYPE_ID = 20710020011);
--exported from THITOH
update T_STRING_RESOURCE
   set (STR_ID, LANG_ID, STR_DATA, ORG_TABLE, UPDATE_TIME) =
       (select 'ERR_20710020011',
               '011',
               'Indx due date is less than paidup date,Please Contact IT Support to correct the data',
               'T_ERROR_TYPE',
               to_date('20180615 18:49:21', 'yyyymmdd hh24:mi:ss')
          from dual)
 where STR_ID = 'ERR_20710020011'
   and LANG_ID = '011';
insert into T_STRING_RESOURCE
  (STR_ID, LANG_ID, STR_DATA, ORG_TABLE, UPDATE_TIME)
  select 'ERR_20710020011',
         '011',
         'Indx due date is less than paidup date,Please Contact IT Support to correct the data',
         'T_ERROR_TYPE',
         to_date('20180615 18:49:21', 'yyyymmdd hh24:mi:ss')
    from dual
   where not exists (select *
            from T_STRING_RESOURCE
           where STR_ID = 'ERR_20710020011'
             and LANG_ID = '011');
             

